version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_task
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local



